name: Self Hosted Runner Test

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: self-hosted

    steps:
      - name: Test Runner
        run: |
          echo "Self-hosted runner is working"
          hostname
          whoami
          uname -a
